spring:
  datasource:
    url: jdbc:mysql://localhost:3306/find_your_perfume?characterEncoding=UTF-8&serverTimezone=UTC
    username: leo
    password: 0000
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis alias & mapper 위치 설정
mybatis:
  type-aliases-package: com.springriders.perfume.*.model
  mapper-locations: mybatis/mapper/**/*.xml

# jsp 수정 후 확인할 수 있는 설정
server:
  servlet:
    jsp:
      init-parameters:
        development: true